In [1]:
# functions

def sum(x, y):
    return(x+y)

In [2]:
sum(2, 4)

6

In [3]:
list = [2, "fksjf", 3]

In [4]:
tuple = (3, 78, 990)

In [6]:
set ={ 4, 6, 8}

In [8]:
multiple_lists =[[3, 2, 0, 1], [0, 3, 7, 2], [7,14,6, 15]]

In [9]:
multiple_lists[0]

[3, 2, 0, 1]

In [10]:
multiple_lists[1]

[0, 3, 7, 2]

In [12]:
#Dictionaries - key value pairs.

dict_multi_list ={'firstlist':[3, 2, 0, 1], 
                  'secondlist': [0, 3, 7, 2],
                  'thirdlist':[7,14,6, 15]} 

In [13]:
display(dict_multi_list)

{'firstlist': [3, 2, 0, 1],
 'secondlist': [0, 3, 7, 2],
 'thirdlist': [7, 14, 6, 15]}

In [14]:
#pandas
#numpy

In [21]:
import pandas as pd
import numpy as np

In [22]:
list_df = pd.DataFrame(dict_multi_list)

In [23]:
list_df

firstlist  secondlist  thirdlist
0          3           0          7
1          2           3         14
2          0           7          6
3          1           2         15

In [24]:
print(list_df.loc[0])

firstlist     3
secondlist    0
thirdlist     7
Name: 0, dtype: int64


In [29]:
print(list_df.loc[[0,2]])

   firstlist  secondlist  thirdlist
0          3           0          7
2          0           7          6


In [30]:
list_df_row_values = pd.DataFrame(dict_multi_list, index=["row1", "row2", "row3", "row4"])

In [31]:
list_df_row_values

firstlist  secondlist  thirdlist
row1          3           0          7
row2          2           3         14
row3          0           7          6
row4          1           2         15

In [32]:
dict_multi_list1 ={'firstlist':[3, 2, 0, 1], 
                  'secondlist': [0, 3, 7, 2],
                  'thirdlist':[7,14,6, 15]} 

In [33]:
dict_multi_list2 ={'firstlist2':[3, 2, 0, 1], 
                  'secondlist2': [0, 3, 7, 2],
                  'thirdlist2':[7,14,6, 15]} 

In [34]:
df1 = pd.DataFrame(dict_multi_list1)
df2 = pd.DataFrame(dict_multi_list2)

In [35]:
display(df1, df2)

firstlist  secondlist  thirdlist
0          3           0          7
1          2           3         14
2          0           7          6
3          1           2         15

firstlist2  secondlist2  thirdlist2
0           3            0           7
1           2            3          14
2           0            7           6
3           1            2          15

In [36]:
pd.concat((df1, df2), axis = 0)

firstlist  secondlist  thirdlist  firstlist2  secondlist2  thirdlist2
0        3.0         0.0        7.0         NaN          NaN         NaN
1        2.0         3.0       14.0         NaN          NaN         NaN
2        0.0         7.0        6.0         NaN          NaN         NaN
3        1.0         2.0       15.0         NaN          NaN         NaN
0        NaN         NaN        NaN         3.0          0.0         7.0
1        NaN         NaN        NaN         2.0          3.0        14.0
2        NaN         NaN        NaN         0.0          7.0         6.0
3        NaN         NaN        NaN         1.0          2.0        15.0

In [37]:
pd.concat((df1, df2), axis = 1)

firstlist  secondlist  thirdlist  firstlist2  secondlist2  thirdlist2
0          3           0          7           3            0           7
1          2           3         14           2            3          14
2          0           7          6           0            7           6
3          1           2         15           1            2          15

In [38]:
list1 = [4, 8, 9]

In [39]:
list1.pop()

9

In [40]:
list1*2

[4, 8, 4, 8]

In [41]:
list_np =np.array([5, 8, 19, 23, 24])

In [42]:
list_np

array([ 5,  8, 19, 23, 24])

In [43]:
list_np.max()

24

In [44]:
list_np*2

array([10, 16, 38, 46, 48])

In [45]:
listnpplus2 = list_np + 2

In [46]:
listnpplus2

array([ 7, 10, 21, 25, 26])

In [47]:
listzeros = np.zeros(4)

In [48]:
listzeros

array([0., 0., 0., 0.])

In [49]:
listzeros = np.ones(4)

In [50]:
listzeros

array([1., 1., 1., 1.])